/* Multilanguage config is not desirable, but it is possible */
/*#define PLAYER "Player"
#define DEFAULT "DefaultPlayer"
#define PLAYER_COUNT "NumberOfPlayers"
#define NAME "Name"
#define RULES "OwnRules"*/
#ifdef LANG_CZ
	#define PLAYER "Hrac"
	#define DEFAULT "Vychozi" PLAYER
	#define PLAYER_COUNT "PocetHracu"
	#define NAME "Jmeno"
	#define RULES "VlastniPravidla"
	#define CUSTOM "vlastni"
	#define PERSON "clovek"
	#define ALGONO "jednoduchy"
	#define PROGRAMMERBOT "stredni"
	#define NETWORKPLAYER "sitovy"
	#define NO "n"
	#define YES "a"
	#define CONTINUE "Chcete hrat dalsi hru [*/" NO "/" YES "]? "
	#define RECEIVED "ziskal"
	#define POINTS "bodu"
	#define CANT_FORCE "nemuze prebijet touto kartou"
	#define LEADS "vede"
	#define NOW "Ted"
	#define ENDS "nechce pokracovat"
	#define USED "pouzil"
	#define END_GAME "Konec hry"
	#define WINNER "Vitez"
	#define WINNERS "Vitezove"
	#define HAS "ma"
	#define LAST_POINT "poslednich 10 bodu"
	#define ERR_NOT_FOUND "Chyba - konfigurace nenalezena"
	#define SAME_CARDS_HAND "ma v ruce 4 stejne karty"
	#define I_AM "Ja jsem "
#else
	#define PLAYER "Player"
	#define DEFAULT "Default" PLAYER
	#define PLAYER_COUNT "NumberOfPlayers"
	#define NAME "Name"
	#define RULES "OwnRules"
	#define CUSTOM "custom"
	#define PERSON "player"
	#define ALGONO "easy"
	#define PROGRAMMERBOT "medium"
	#define NETWORKPLAYER "network"
	#define NO "n"
	#define YES "y"
	#define CONTINUE "Do you want to play a next game [*/" NO "/" YES "]? "
	#define RECEIVED "received"
	#define POINTS "points"
	#define CANT_FORCE "cant force next loop with this card"
	#define LEADS "leads this hand"
	#define NOW "Now"
	#define ENDS "don't want to continue"
	#define USED "used"
	#define END_GAME "End of the game"
	#define WINNER "Winner"
	#define WINNERS "Winners"
	#define HAS "has"
	#define LAST_POINT "last 10 points"
	#define ERR_NOT_FOUND "Error - configuration not found"
	#define SAME_CARDS_HAND "has 4 same cards"
	#define I_AM "I am "
#endif
